name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup AWS CDK
      run: npm install -g aws-cdk@1.98.0

    - name: Lambda test
      run: |
        cd lambda/HelloHandler/test/HelloHandler.Tests
        dotnet test

    - name: Build
      run: |
        cd lambda/HelloHandler/src/HelloHandler
        dotnet publish

    - name: Deploy
      env:
        AWS_DEFAULT_REGION: 'ap-northeast-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: cdk deploy --require-approval "never"